//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.24 at 11:43:42 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.opentravel.org/OTA/2002/11", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sabre.web_services.sessionCreate.sessionCreateRQ;
