//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.03 at 07:05:53 PM EET 
//


package com.sabre.web_services.sessionCreate.sessionCreateRS;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sabre.web_services.sessionCreate.sessionCreateRS package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sabre.web_services.sessionCreate.sessionCreateRS
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SessionCreateRS }
     * 
     */
    public SessionCreateRS createSessionCreateRS() {
        return new SessionCreateRS();
    }

    /**
     * Create an instance of {@link SessionCreateRS.Errors }
     * 
     */
    public SessionCreateRS.Errors createSessionCreateRSErrors() {
        return new SessionCreateRS.Errors();
    }

    /**
     * Create an instance of {@link SessionCreateRS.Errors.Error }
     * 
     */
    public SessionCreateRS.Errors.Error createSessionCreateRSErrorsError() {
        return new SessionCreateRS.Errors.Error();
    }

    /**
     * Create an instance of {@link SessionCreateRS.Warnings }
     * 
     */
    public SessionCreateRS.Warnings createSessionCreateRSWarnings() {
        return new SessionCreateRS.Warnings();
    }

    /**
     * Create an instance of {@link SessionCreateRS.Success }
     * 
     */
    public SessionCreateRS.Success createSessionCreateRSSuccess() {
        return new SessionCreateRS.Success();
    }

    /**
     * Create an instance of {@link SessionCreateRS.Errors.Error.ErrorInfo }
     * 
     */
    public SessionCreateRS.Errors.Error.ErrorInfo createSessionCreateRSErrorsErrorErrorInfo() {
        return new SessionCreateRS.Errors.Error.ErrorInfo();
    }

    /**
     * Create an instance of {@link SessionCreateRS.Warnings.Warning }
     * 
     */
    public SessionCreateRS.Warnings.Warning createSessionCreateRSWarningsWarning() {
        return new SessionCreateRS.Warnings.Warning();
    }

}
