//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.03 at 07:08:12 PM EET 
//


package com.sabre.web_services.sabreCommandLLS1_8_1.sabreCommandLLS1_8_1RS;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sabre.web_services.sabreCommandLLS1_8_1.sabreCommandLLS1_8_1RS package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sabre.web_services.sabreCommandLLS1_8_1.sabreCommandLLS1_8_1RS
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SabreCommandLLSRS }
     * 
     */
    public SabreCommandLLSRS createSabreCommandLLSRS() {
        return new SabreCommandLLSRS();
    }

    /**
     * Create an instance of {@link SabreCommandLLSRS.ErrorRS }
     * 
     */
    public SabreCommandLLSRS.ErrorRS createSabreCommandLLSRSErrorRS() {
        return new SabreCommandLLSRS.ErrorRS();
    }

    /**
     * Create an instance of {@link SabreCommandLLSRS.ErrorRS.Errors }
     * 
     */
    public SabreCommandLLSRS.ErrorRS.Errors createSabreCommandLLSRSErrorRSErrors() {
        return new SabreCommandLLSRS.ErrorRS.Errors();
    }

    /**
     * Create an instance of {@link SabreCommandLLSRS.ErrorRS.Errors.Error }
     * 
     */
    public SabreCommandLLSRS.ErrorRS.Errors.Error createSabreCommandLLSRSErrorRSErrorsError() {
        return new SabreCommandLLSRS.ErrorRS.Errors.Error();
    }

    /**
     * Create an instance of {@link SabreCommandLLSRS.XMLContent }
     * 
     */
    public SabreCommandLLSRS.XMLContent createSabreCommandLLSRSXMLContent() {
        return new SabreCommandLLSRS.XMLContent();
    }

    /**
     * Create an instance of {@link SabreCommandLLSRS.ErrorRS.Errors.Error.ErrorInfo }
     * 
     */
    public SabreCommandLLSRS.ErrorRS.Errors.Error.ErrorInfo createSabreCommandLLSRSErrorRSErrorsErrorErrorInfo() {
        return new SabreCommandLLSRS.ErrorRS.Errors.Error.ErrorInfo();
    }

}
