//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.03 at 07:08:12 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.sabre.com/sabreXML/2003/07", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sabre.web_services.sabreCommandLLS1_8_1.sabreCommandLLS1_8_1RS;
