//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 09:25:36 PM EEST 
//


package com.sabre.web_services.queueAccessLLS2_0_9.queueAccessLLS2_0_9RQ;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sabre.web_services.queueAccessLLS2_0_9.queueAccessLLS2_0_9RQ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sabre.web_services.queueAccessLLS2_0_9.queueAccessLLS2_0_9RQ
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueueAccessRQ }
     * 
     */
    public QueueAccessRQ createQueueAccessRQ() {
        return new QueueAccessRQ();
    }

    /**
     * Create an instance of {@link QueueAccessRQ.QueueIdentifier }
     * 
     */
    public QueueAccessRQ.QueueIdentifier createQueueAccessRQQueueIdentifier() {
        return new QueueAccessRQ.QueueIdentifier();
    }

    /**
     * Create an instance of {@link QueueAccessRQ.Navigation }
     * 
     */
    public QueueAccessRQ.Navigation createQueueAccessRQNavigation() {
        return new QueueAccessRQ.Navigation();
    }

    /**
     * Create an instance of {@link QueueAccessRQ.Selection }
     * 
     */
    public QueueAccessRQ.Selection createQueueAccessRQSelection() {
        return new QueueAccessRQ.Selection();
    }

    /**
     * Create an instance of {@link QueueAccessRQ.QueueIdentifier.List }
     * 
     */
    public QueueAccessRQ.QueueIdentifier.List createQueueAccessRQQueueIdentifierList() {
        return new QueueAccessRQ.QueueIdentifier.List();
    }

    /**
     * Create an instance of {@link QueueAccessRQ.Navigation.Direction }
     * 
     */
    public QueueAccessRQ.Navigation.Direction createQueueAccessRQNavigationDirection() {
        return new QueueAccessRQ.Navigation.Direction();
    }

}
