//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 09:25:36 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.sabre.com/sabreXML/2011/10", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sabre.web_services.queueAccessLLS2_0_9.queueAccessLLS2_0_9RQ;
