//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.03 at 07:06:31 PM EET 
//


package com.sabre.web_services.sessionClose.sessionCloseRS;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sabre.web_services.sessionClose.sessionCloseRS package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sabre.web_services.sessionClose.sessionCloseRS
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SessionCloseRS }
     * 
     */
    public SessionCloseRS createSessionCloseRS() {
        return new SessionCloseRS();
    }

    /**
     * Create an instance of {@link SessionCloseRS.Errors }
     * 
     */
    public SessionCloseRS.Errors createSessionCloseRSErrors() {
        return new SessionCloseRS.Errors();
    }

    /**
     * Create an instance of {@link SessionCloseRS.Errors.Error }
     * 
     */
    public SessionCloseRS.Errors.Error createSessionCloseRSErrorsError() {
        return new SessionCloseRS.Errors.Error();
    }

    /**
     * Create an instance of {@link SessionCloseRS.Warnings }
     * 
     */
    public SessionCloseRS.Warnings createSessionCloseRSWarnings() {
        return new SessionCloseRS.Warnings();
    }

    /**
     * Create an instance of {@link SessionCloseRS.Success }
     * 
     */
    public SessionCloseRS.Success createSessionCloseRSSuccess() {
        return new SessionCloseRS.Success();
    }

    /**
     * Create an instance of {@link SessionCloseRS.Errors.Error.ErrorInfo }
     * 
     */
    public SessionCloseRS.Errors.Error.ErrorInfo createSessionCloseRSErrorsErrorErrorInfo() {
        return new SessionCloseRS.Errors.Error.ErrorInfo();
    }

    /**
     * Create an instance of {@link SessionCloseRS.Warnings.Warning }
     * 
     */
    public SessionCloseRS.Warnings.Warning createSessionCloseRSWarningsWarning() {
        return new SessionCloseRS.Warnings.Warning();
    }

}
